[build]
  command = "bun run build"
  publish = "dist"

[functions]
  # Increase the timeout for Firebase operations if needed (in seconds)
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "#custom"
  command = "bun run dev"
  targetPort = 5173
  publish = "dist"
  # Allow local environment variables to be used in development
  [dev.environment]
    NODE_VERSION = "22.15.0"

# Required CORS headers for local development
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"
